# Generated by Django 3.1.7 on 2023-11-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BDprincipal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_edificio', models.CharField(max_length=100)),
                ('Apartamento', models.CharField(max_length=80)),
                ('Habitaciones', models.CharField(max_length=60)),
                ('Propietario', models.CharField(max_length=60)),
                ('Baños', models.CharField(max_length=50)),
            ],
        ),
    ]
